name: 'Export all vars/secrets to env variables'
description: 'Utility action that exports all github vars/secrets to environment variables'
author: 'Daniele Franceschi @danielefranceschi'
inputs:
  secrets:
    required: true
    description: JSON representation of the vars/secrets, use provided placeholder'
  prefix:
    required: false
    description: 'Prefix to add to all secrets, e.g.: SECRET_'
  include:
    required: false
    description: 'Comma-separated list of secrets to export'
  exclude:
    required: false
    description: 'Comma-separated list of secrets to skip exporting'
  convert:
    required: false
    description: 'Converts secrets name to a specific string case (default: upper)'
  override:
    required: false
    description: 'Override existing environment variables (false by default)'
  removeprefix:
    required: false
    description: 'Remove prefix from secrets name, if present'
  tracelog:
    required: false
    description: 'extensive debug logging (false by default)'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: book-open
  color: orange
